// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-_Q7OKxa57QEyNssm-YVou61_5aJXMqw',
    appId: '1:1039948055297:android:97f216c45ef6fa29495100',
    messagingSenderId: '1039948055297',
    projectId: 'tenka-caisse',
    storageBucket: 'tenka-caisse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-_Q7OKxa57QEyNssm-YVou61_5aJXMqw',
    appId: '1:1039948055297:ios:97f216c45ef6fa29495100',
    messagingSenderId: '1039948055297',
    projectId: 'tenka-caisse',
    storageBucket: 'tenka-caisse.appspot.com',
    iosBundleId: 'com.example.tenkaCaisse',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-_Q7OKxa57QEyNssm-YVou61_5aJXMqw',
    appId: '1:1039948055297:web:97f216c45ef6fa29495100',
    messagingSenderId: '1039948055297',
    projectId: 'tenka-caisse',
    authDomain: 'tenka-caisse.firebaseapp.com',
    storageBucket: 'tenka-caisse.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-_Q7OKxa57QEyNssm-YVou61_5aJXMqw',
    appId: '1:1039948055297:macos:97f216c45ef6fa29495100',
    messagingSenderId: '1039948055297',
    projectId: 'tenka-caisse',
    storageBucket: 'tenka-caisse.appspot.com',
    iosBundleId: 'com.example.tenkaCaisse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-_Q7OKxa57QEyNssm-YVou61_5aJXMqw',
    appId: '1:1039948055297:windows:97f216c45ef6fa29495100',
    messagingSenderId: '1039948055297',
    projectId: 'tenka-caisse',
    storageBucket: 'tenka-caisse.appspot.com',
  );
}
